namespace Frends.CSV.ConvertToJSON;

using CsvHelper;
using CsvHelper.Configuration;
using Frends.CSV.ConvertToJSON.Definitions;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.IO;
using System.Threading;

/// <summary>
/// CSV Task.
/// </summary>
public static class CSV
{
    /// <summary>
    /// Converts CSV string content to JSON string.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.CSV.ConvertToJSON)
    /// </summary>
    /// <param name="input">Input parameters</param>
    /// <param name="options">Optional parameters</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this Task.</param>
    /// <returns>Object { bool Success, JToken Json }</returns>
    public static Result ConvertToJSON([PropertyTab] Input input, [PropertyTab] Options options, CancellationToken cancellationToken)
    {
        var cultureInfo = new CultureInfo(options.CultureInfo);
        int columnCount = input.ColumnSpecifications.Length;
        bool hasColumnSpecs = columnCount > 0;

        using var writer = new JTokenWriter();
        writer.Formatting = Newtonsoft.Json.Formatting.Indented;
        writer.Culture = cultureInfo;
        writer.WriteStartArray();

        var configuration = new CsvConfiguration(cultureInfo)
        {
            HasHeaderRecord = options.ContainsHeaderRow,
            Delimiter = input.Delimiter,
            TrimOptions = options.TrimOutput ? TrimOptions.None : TrimOptions.Trim,
            IgnoreBlankLines = options.SkipEmptyRows,
            Mode = options.IgnoreQuotes ? CsvMode.NoEscape : CsvMode.RFC4180,
        };

        // Setting the MissingFieldFound -delegate property of configuration to null when
        // option.TreatMissingFieldsAsNulls is set to true for returning null values for missing fields.
        // Otherwise the default setting which throws a MissingFieldException is used
        if (options.TreatMissingFieldsAsNulls)
            configuration.MissingFieldFound = null;

        using TextReader sr = new StringReader(input.Csv);

        // Read rows before passing textreader to csvreader for so that header row would be in the correct place
        for (var i = 0; i < options.SkipRowsFromTop; i++)
            _ = sr.ReadLine();

        using var csvReader = new CsvReader(sr, configuration);
        if (options.ContainsHeaderRow)
        {
            csvReader.Read();
            csvReader.ReadHeader();
        }

        if (hasColumnSpecs)
        {
            var headers = new List<string>();
            var typeList = new List<Type>();

            foreach (var columnSpec in input.ColumnSpecifications)
            {
                typeList.Add(ToType(columnSpec.Type, options.TreatMissingFieldsAsNulls));
                headers.Add(columnSpec.Name);
            }

            while (csvReader.Read())
            {
                cancellationToken.ThrowIfCancellationRequested();
                writer.WriteStartObject();

                for (var index = 0; index < columnCount; index++)
                {
                    writer.WritePropertyName(headers[index]);
                    writer.WriteValue(csvReader.GetField(typeList[index], index));
                }

                writer.WriteEndObject();
            }
        }
        else if (options.ContainsHeaderRow)
        {
            var headerRecord = csvReader.HeaderRecord;
            var headers = new List<string>(headerRecord.Length);

            if (string.Equals(options.ReplaceHeaderWhitespaceWith, " "))
                headers.AddRange(headerRecord);
            else
            {
                foreach (var h in headerRecord)
                    headers.Add(h.Replace(" ", options.ReplaceHeaderWhitespaceWith));
            }

            int headerCount = headers.Count;
            while (csvReader.Read())
            {
                cancellationToken.ThrowIfCancellationRequested();
                writer.WriteStartObject();

                for (var index = 0; index < headerCount; index++)
                {
                    writer.WritePropertyName(headers[index]);
                    writer.WriteValue(csvReader.GetField(index));
                }

                writer.WriteEndObject();
            }
        }
        else
        {
            if (!csvReader.Read())
                throw new ArgumentException("CSV input can not be empty");

            var record = csvReader.Parser.Record;
            var headers = new List<string>(record.Length);

            for (int i = 0; i < record.Length; i++)
                headers.Add(i.ToString());

            int headerCount = headers.Count;
            writer.WriteStartObject();
            for (var index = 0; index < headerCount; index++)
            {
                writer.WritePropertyName(headers[index]);
                writer.WriteValue(csvReader.GetField(index));
            }
            writer.WriteEndObject();

            while (csvReader.Read())
            {
                cancellationToken.ThrowIfCancellationRequested();

                writer.WriteStartObject();

                for (var index = 0; index < headerCount; index++)
                {
                    writer.WritePropertyName(headers[index]);
                    writer.WriteValue(csvReader.GetField(index));
                }

                writer.WriteEndObject();
            }
        }

        writer.WriteEndArray();
        return new Result(true, writer.Token);

    }

    private static Type ToType(ColumnType code, bool useNullables)
    {
        return code switch
        {
            ColumnType.Boolean => useNullables ? typeof(bool?) : typeof(bool),
            ColumnType.Char => useNullables ? typeof(char?) : typeof(char),
            ColumnType.DateTime => useNullables ? typeof(DateTime?) : typeof(DateTime),
            ColumnType.Decimal => useNullables ? typeof(decimal?) : typeof(decimal),
            ColumnType.Double => useNullables ? typeof(double?) : typeof(double),
            ColumnType.Int => useNullables ? typeof(int?) : typeof(int),
            ColumnType.Long => useNullables ? typeof(long?) : typeof(long),
            ColumnType.String => typeof(string),
            _ => null,
        };
    }

}