using System.ComponentModel;
using System.Globalization;
using System.Threading;
using CsvHelper;
using CsvHelper.Configuration;
using Frends.CSV.Create.Definitions;
using Frends.CSV.Create.Parsers;

namespace Frends.CSV.Create;

/// <summary>
/// CSV Task.
/// </summary>
public static class CSV
{
    /// <summary>
    /// Create a CSV string from a List, JSON string or XML string.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.CSV.Create)
    /// </summary>
    /// <param name="input">Input parameters</param>
    /// <param name="options">Optional parameters</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this Task.</param>
    /// <returns>Object { bool Success, string CSV }</returns>
    public static Result Create([PropertyTab] Input input, [PropertyTab] Options options, CancellationToken cancellationToken)
    {
        var config = new CsvConfiguration(new CultureInfo(options.CultureInfo))
        {
            Delimiter = input.Delimiter,
            HasHeaderRecord = options.IncludeHeaderRow
        };

        if (options.NeverAddQuotesAroundValues)
        {
            config.Mode = CsvMode.NoEscape;
            // if IgnoreQuotes is true, seems like ShouldQuote function has to return false in all cases
            // if IgnoreQuotes is false ShouldQuote can't have any implementation otherwise it will overwrite IgnoreQuotes statement ( might turn it on again)
            config.ShouldQuote = _ => !options.NeverAddQuotesAroundValues;
        }

        var csv = input.InputType switch
        {
            CreateInputType.List => ListParser.ListToCsvString(input.Data, input.Headers, config, options,
                cancellationToken),
            CreateInputType.Json => JsonParserNew.JsonToCsvString(input, config, options, cancellationToken),
            CreateInputType.Xml => XmlParser.XmlToCsvString(input.Xml, input.XmlNodeElementName, config, options,
                cancellationToken),
            _ => string.Empty
        };
        return new Result(true, csv);
    }



}