name: ConvertToXML build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.CSV.ConvertToXML/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.CSV.ConvertToXML
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}